- platform: "Github"
  link: "https://github.com/JeremyTran211?tab=repositories"

- platform: "Linkedin"
  link: "https://www.linkedin.com/in/jeremy-tran-569685266/"

- platform: "Facebook"
  link: "https://linkedin.com/in/JeremyTran211"

