- platform: "Github"
  link: "https://github.com/JeremyTran211?tab=repositories"

- platform: "Linkedin"
  link: "https://linkedin.com/in/JeremyTran211"

- platform: "Facebook"
  link: "https://linkedin.com/in/JeremyTran211"

